services:
  dev:
    build: .
    container_name: smarthome
    working_dir: /workspace

    volumes:
      - ./:/workspace

    ports:
      - "10011:10011/tcp"
      - "10011:10011/udp"
      - "9092-9093:9092-9093/tcp"
      - "50042:50042/tcp"

    tty: true
